// <auto-generated />
namespace M17E_TrabalhoModelo_2020_21_WIP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class estadia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(estadia));
        
        string IMigrationMetadata.Id
        {
            get { return "202104061005487_estadia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
